apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploynet8ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploynet8ubuntu
  template:
    metadata:
      labels:
        app: deploynet8ubuntu
    spec:
      containers:
      - name: deploynet8ubuntu
        image: deploynet8ubuntu:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5876
