name: CI/CD Deploy to KinD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t deploynet8ubuntu:latest .

    - name: Load Docker image into KinD
      run: kind load docker-image deploynet8ubuntu:latest

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s/

    # Port Forwarding cần chạy trong một background process và giữ sống trong suốt quá trình CI/CD
    - name: Start port-forwarding in background
      run: |
        nohup kubectl port-forward service/deploynet8ubuntu-service 5876:80 &
        sleep 5  # Đảm bảo rằng port-forward đã sẵn sàng

    - name: kubectl rollout restart deployment
      run: kubectl rollout restart deployment/deploynet8ubuntu

    - name: Check pod status
      run: kubectl get pods
