name: CI/CD Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/deploynet8ubuntu:${{ github.sha }} .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/deploynet8ubuntu:${{ github.sha }}

      - name: Deploy locally on WSL
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/deploynet8ubuntu:${{ github.sha }}
          docker stop deploynet8ubuntu || true
          docker rm deploynet8ubuntu || true
          docker run -d -p 5876:5876 --name deploynet8ubuntu ${{ secrets.DOCKER_USERNAME }}/deploynet8ubuntu:${{ github.sha }}
