name: CI/CD Deploy to KinD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t DeployNET8Ubuntu:latest .

    - name: Load Docker image into KinD
      run: kind load docker-image DeployNET8Ubuntu:latest

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s/
